# Single-container deploy (Hugging Face Spaces / any Docker host).
# FastAPI orchestrator + embedder + reranker + embedded Qdrant + student portal.
# CPU-only. The LLM is a hosted OpenAI-compatible API (set via env).
#
# Pinned by DIGEST, not by tag. `python:3.11-slim` is a moving target: the same
# Dockerfile built a month apart produces different images, so a rebuild of a
# release tag is not the artifact that was tested. Refresh deliberately with:
#   docker pull python:3.11-slim
#   docker inspect --format='{{index .RepoDigests 0}}' python:3.11-slim
# Resolved from the registry on 2026-08-05; tag at that time: 3.11-slim.
FROM python@sha256:94c50be2dc994b873b55bc123e95e6dbade08095b3dfd790f51c34de3f08cbb7

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    # Model cache baked into the image (below) so cold starts don't re-download
    # the ~2GB embedder + reranker. Kept under /app so it survives in the layer.
    HF_HOME=/app/.cache/hf \
    # Weights are baked in, so runtime must not talk to huggingface.co at all.
    # Without this, every model load first issues HEAD requests to check for
    # updates; when the hub is slow or unreachable those calls retry and can
    # burn minutes of the launch window before a single byte is served.
    HF_HUB_OFFLINE=1 \
    TRANSFORMERS_OFFLINE=1 \
    HF_HUB_DISABLE_TELEMETRY=1 \
    # Embedded Qdrant storage. Declared here rather than only as a dashboard
    # variable, so the container's behaviour is visible in the repo and a fresh
    # deploy can't miss it. /tmp because the app dir is read-only on HF Spaces.
    QDRANT_PATH=/tmp/qdrant \
    ENVIRONMENT=production \
    # Production serves the prebuilt corpus artifact; embedding at boot is the
    # slow path that caused the launch timeout.
    ALLOW_INDEX_BUILD_ON_BOOT=0 \
    # Two cores, one model copy: keep generation concurrency small.
    MAX_CONCURRENT_GENERATIONS=2

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

# Runtime dependencies from a locked, fully hashed resolution.
#
# This replaces `pip install torch --index-url …` followed by an unpinned
# `pip install -e .`, which resolved fresh on every build: two builds of the
# same commit could install different versions, and nothing verified what came
# down the wire. requirements.lock.txt is generated by scripts/lock_deps.py from
# uv.lock and carries a hash for every artifact, so --require-hashes makes the
# install both reproducible and tamper-evident.
#
# The extra index supplies torch's Linux CPU wheels (torch==2.13.0+cpu); pinning
# that in pyproject.toml is what keeps the ~2 GB nvidia-* CUDA stack out of a
# CPU-only image. Dev-only packages (pytest) are excluded by --no-dev at export.
COPY requirements.lock.txt ./
RUN pip install --no-cache-dir --require-hashes \
      --extra-index-url https://download.pytorch.org/whl/cpu \
      -r requirements.lock.txt

# Editable install so `ritaj` keeps importing from /app/src (api.py resolves the
# portal path relative to the source tree). --no-deps because the lock above
# already installed them, hash-verified; without it pip would re-resolve and
# quietly undo the pinning.
COPY pyproject.toml ./
COPY src ./src
RUN pip install --no-cache-dir --no-deps -e .

# Pre-download (bake) the embedder + reranker into the image, at the SAME
# revisions config.py loads at runtime. A bare repo name resolves to whatever is
# on the hub that day, so an unpinned rebuild can bake different weights than
# the ones the release evaluation was run against.
ARG EMBED_REVISION=3d7cfbdacd47fdda877c5cd8a79fbcc4f2a574f3
ARG RERANK_REVISION=953dc6f6f85a1b2dbfca4c34a2796e7dde08d41e
RUN python -c "from sentence_transformers import SentenceTransformer, CrossEncoder; \
SentenceTransformer('intfloat/multilingual-e5-large', revision='${EMBED_REVISION}'); \
CrossEncoder('BAAI/bge-reranker-v2-m3', revision='${RERANK_REVISION}')"

COPY data ./data
COPY scripts ./scripts
COPY ritaj-student-portal/dist ./ritaj-student-portal/dist

# HF Spaces runs as a non-root user (UID 1000): make caches/app readable+writable.
RUN chmod +x scripts/start.sh && chmod -R 777 /app/.cache

# HF Spaces serves on 7860; start.sh binds uvicorn to $PORT (default 7860).
EXPOSE 7860

# Liveness only. /ready would report the container unhealthy during the normal
# warm-up and get it restarted in a loop — exactly the failure mode this
# deployment is recovering from. Readiness is for withholding traffic, not for
# deciding whether to kill the process.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD curl -fsS "http://localhost:${PORT:-7860}/live" || exit 1

CMD ["scripts/start.sh"]
