// Talks to the Ritaj RAG backend's streaming endpoint (POST /chat/stream).
//
// The backend speaks Server-Sent Events. Because the endpoint is POST (EventSource
// only does GET), we read the response body as a stream and parse the `data:` frames
// ourselves. Event shapes (see src/ritaj/api.py):
//   { type: 'sources',   sources: [...] }          // opening event (ignored for now)
//   { type: 'injection', injection: {...} }         // adversarial chunk flagged (ignored)
//   { type: 'token',     text: '...' }              // one answer delta
//   { type: 'grounding', grounding: {...} }         // verdict (ignored for now)
//   { type: 'repair',    answer: '...' }            // guardrail withheld the draft
//   { type: 'links',     links: [{label, url}] }    // page links for the cited docs
//   { type: 'about',     answer, images: [{url, caption}] }  // who-made-this credit
//   { type: 'blocked',   category, answer }          // scope guardrail declined the input
//   { type: 'error',     message: '...' }
//   { type: 'done' }

// A deterministic page link for a cited source doc (built server-side from
// data/links.yaml — never generated by the model).
export type PageLink = { label: string; url: string }

// A team photo shown with the "who made this?" credit answer.
export type TeamImage = { url: string; caption?: string }

// Hide inline source citations ([1], [2], and runs like "[1]، [2]، [3]" with
// English or Arabic separators) from the student-facing text. The markers stay
// in the server's answer — grounding.py verifies them and links.py maps them to
// page URLs — so we only strip them at render, never upstream. Also drops a
// trailing half-typed marker mid-stream (e.g. "[" or "[12" before its closing
// "]" has streamed in) so no broken bracket flickers as tokens arrive.
export function stripCitations(text: string): string {
  return text
    // a run of one or more [n] markers joined by spaces / commas (incl. Arabic ،)
    .replace(/\s*\[\d+\](?:\s*[،,]\s*\[\d+\])*/g, '')
    // a trailing, still-incomplete marker that hasn't closed yet (streaming)
    .replace(/\s*\[\d*$/g, '')
    // tidy whitespace a removed marker may have left before punctuation / doubled
    .replace(/[ \t]+([.!?؟،,])/g, '$1')
    .replace(/[ \t]{2,}/g, ' ')
}

export type StreamCallbacks = {
  onToken?: (text: string) => void
  onBlocked?: (answer: string, category: string) => void
  onRepair?: (answer: string) => void
  onLinks?: (links: PageLink[]) => void
  onAbout?: (answer: string, images: TeamImage[]) => void
  // `code` is the backend's stable error code when it sent one, so the UI can
  // choose its own wording (and its own advice) per failure rather than
  // showing one generic sentence for every possible cause.
  onError?: (message: string, code?: string, requestId?: string) => void
  onDone?: () => void
}

// One prior conversation turn, sent back with each request so the backend can
// answer follow-ups ("and what about summer?"). The server stays stateless —
// the client owns the conversation and replays it every message.
export type ChatTurn = { role: 'user' | 'assistant'; content: string }

export type ChatMeta = {
  history?: ChatTurn[]
  // Groups this conversation's turns in the aggregate log. Client-generated and
  // random: it identifies a chat, not a student. There is deliberately no name
  // field — the portal does not ask for one (roadmap Phase 8).
  sessionId?: string
}

/**
 * Why the request never produced a response.
 *
 * `fetch` rejects with an opaque `TypeError: "Failed to fetch"` for DNS failure,
 * a refused connection, a TLS problem, a blocked request and a CORS rejection
 * alike — the Fetch spec deliberately withholds which, because distinguishing
 * them would let any page probe the user's network. So this classifies what it
 * honestly can (offline, timed out, cancelled) and says plainly that it cannot
 * separate the rest, rather than guessing at a cause and being wrong.
 *
 * The portal calls its own origin, so "unreachable" here almost always means the
 * server itself is down, restarting, or asleep — which is worth saying, because
 * "check your connection" is misleading advice when the student's connection is
 * demonstrably fine (they loaded this page over it).
 */
export type TransportFailure = { code: string; detail?: string }

export function describeTransportFailure(err: unknown): TransportFailure {
  const error = err as { name?: string; message?: string }

  if (typeof navigator !== 'undefined' && navigator.onLine === false) {
    return { code: 'OFFLINE' }
  }
  if (error?.name === 'TimeoutError') return { code: 'TIMEOUT' }
  if (error?.name === 'AbortError') return { code: 'ABORTED' }
  if (error?.name === 'TypeError') {
    // Keep the browser's own wording as detail — it differs per engine and is
    // the only thing a bug report can be correlated against.
    return { code: 'UNREACHABLE', detail: error.message }
  }
  return { code: 'UNKNOWN', detail: error?.message }
}

/** A status-derived code for a response whose body was not the expected JSON. */
function statusCode(status: number): string {
  if (status === 503) return 'STARTING_OR_ASLEEP'
  if (status === 502 || status === 504) return 'GATEWAY'
  if (status === 429) return 'RATE_LIMITED'
  if (status === 413) return 'REQUEST_TOO_LARGE'
  return 'HTTP_ERROR'
}

export async function streamChat(
  message: string,
  callbacks: StreamCallbacks,
  meta: ChatMeta = {},
  signal?: AbortSignal,
): Promise<void> {
  let finished = false
  const finish = () => {
    if (finished) return
    finished = true
    callbacks.onDone?.()
  }

  try {
    const response = await fetch('/v2/chat/stream', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message,
        history: meta.history ?? [],
        session_id: meta.sessionId ?? null,
        client: 'portal',
        locale: document.documentElement.lang === 'ar' ? 'ar' : 'en',
      }),
      signal,
    })
    if (!response.ok || !response.body) {
      // The backend refuses with a STABLE CODE and a written message
      // (src/ritaj/errors.py), e.g. {"code":"NO_CORPUS","message":"..."}.
      // This used to discard all of it and report `HTTP 503`, which the UI then
      // replaced with "Couldn't reach the assistant right now. Please try
      // again." — a network-failure message for a service that answered
      // clearly, and advice ("try again") that can never come true when the
      // cause is an unpublished corpus.
      let code: string | null = null
      let message: string | null = null
      try {
        const body = await response.json()
        code = typeof body?.code === 'string' ? body.code : null
        message = typeof body?.message === 'string' ? body.message : null
      } catch {
        // Not our JSON. A sleeping or still-building Space is served an HTML
        // page by the platform proxy, never by this application, so the status
        // is the only signal left — and it is a much better one than the bare
        // number the UI used to print.
        code = statusCode(response.status)
      }
      // The request id is the join key to the protected server log, so a
      // failure can be reported without repeating the question.
      const requestId = response.headers.get('X-Request-ID') ?? undefined
      callbacks.onError?.(message ?? `HTTP ${response.status}`, code ?? undefined, requestId)
      return finish()
    }

    const reader = response.body.getReader()
    const decoder = new TextDecoder()
    let buffer = ''

    for (;;) {
      const { value, done } = await reader.read()
      if (done) break
      buffer += decoder.decode(value, { stream: true })

      // SSE frames are separated by a blank line; keep the trailing partial.
      const frames = buffer.split('\n\n')
      buffer = frames.pop() ?? ''
      for (const frame of frames) {
        const line = frame.split('\n').find((l) => l.startsWith('data:'))
        if (!line) continue
        const payload = line.slice(5).trim()
        if (!payload) continue

        let event: { type: string; [k: string]: unknown }
        try {
          event = JSON.parse(payload)
        } catch {
          continue
        }

        switch (event.type) {
          case 'token':
            callbacks.onToken?.(event.text as string)
            break
          case 'blocked':
            callbacks.onBlocked?.(event.answer as string, event.category as string)
            break
          case 'repair':
            callbacks.onRepair?.(event.answer as string)
            break
          case 'links':
            callbacks.onLinks?.((event.links as PageLink[]) ?? [])
            break
          case 'about':
            callbacks.onAbout?.(event.answer as string, (event.images as TeamImage[]) ?? [])
            break
          case 'error':
            callbacks.onError?.(event.message as string, event.code as string | undefined)
            break
          case 'done':
            return finish()
          // sources / grounding / injection: no UI slot yet, intentionally ignored.
        }
      }
    }
  } catch (err) {
    const failure = describeTransportFailure(err)
    // A cancellation is the student pressing stop, not a failure to report.
    if (failure.code !== 'ABORTED') {
      callbacks.onError?.(failure.detail ?? failure.code, failure.code)
    }
  } finally {
    finish()
  }
}
